# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa53ef09b539134b95a48b829bdf33c527ca029386beb4fbed497adb6adc4b6f8ce797eae216bb267fedcf993999398519521e7f1efe9c4c9a036297b7531d02

test:
  secret_key_base: ac0dff8db4a222a8454123707983738a77e256a46ca00a1bfbe2088b668eb3e486fb63277c180cad9478685c5682768e32a18fd5b506899292881a1ead70b23d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
